# Generated by Django 6.0.4 on 2026-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('inserido_em', models.DateTimeField(auto_now_add=True)),
                ('sentimento', models.CharField(max_length=20)),
                ('tema', models.CharField(max_length=50)),
            ],
        ),
    ]
